config/routes.rb
Rails.application.routes.draw do


  root 'sessions#new'
  get  'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :staffs
  resources :places
  resources :features do
    resources :needs
  end
  resources :students
  resources :requests do
    collection do
      get :prints
      get :batch_print
      post :batch
      delete :delete_batch
    end
  end
  resources :sessions
  resources :forms
  resources :request_students
  resources :messages
  resources :import_students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :place, optional: true
  attr_accessor :remember_token
	
  VALID_FARSI_REGEX = /\A[اآبپتثئجچحخدذرزژسشصضطظعغفقکگلمنوهیءأؤّ\s]+\z/
  validates :f_name, presence: {message: "نام نمی تواند خالی باشد."},
                     length: { maximum: 25, message:"نام می تواند حداکثر ۲۵ نویسه باشد" },
                     format: {with: VALID_FARSI_REGEX, message: "نام باید فارسی باشد."}
  validates :l_name, presence: {message: "نام خانوادگی نمی تواند خالی باشد."},
                     length: { maximum: 30, message:"نام خانوادگی می تواند حداکثر ۳۰ نویسه باشد" },
                     format: {with: VALID_FARSI_REGEX, message: "نام خانوادگی باید فارسی باشد."}
  has_secure_password validation: false
  validates :password,presence:{message: "پسورد نمی تواند خالی باشد."}, length: { minimum: 6, message: "رمز عبور باید حداقل ۶ نویسه باشد." },on: :create

  validates :username, presence: {message: "نام کاربری نمی تواند خالی باشد."},
                       length: { within: 5..25, too_long:"نام کاربری باید حداقل 5 نویسه باشد.", too_short:"نام کاربری می تواند حداکثر 25 نویسه باشد." },
                       uniqueness: { case_sensitive: false, message: "نام کاربری قبلاْ استفاده شده است." }

	scope :sorted,lambda{order("f_name ASC")}


  #Returns the hash digest of the given string.
	#need for testing
	def Staff.digest(string)
		#https://github.com/rails/rails/blob/master/activemodel/lib/active_model/secure_password.rb
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
																									BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	#Returns a random token.
	def Staff.new_token
		SecureRandom.urlsafe_base64
	end

	#use like @current_user.remember
	def remember
		#remember_token is virtual attribute
		self.remember_token = Staff.new_token
		update_attribute(:remember_digest, Staff.digest(remember_token))
	end

	#Forgets a user
	def forget
		update_attribute(:remember_digest, nil)
	end

	#Returns true if  the given token matches the digest
	def authenticated?(remember_token)
		return false if remember_digest.nil? #Prevents error (bug fix)
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :staff_logged_in
  layout "staff/admin"
  def index
    @staffs=Staff.sorted
  end

  def new
    @staff=Staff.new
  end

  def create
    @staff=Staff.new(staff_params)
      respond_to do |format|
        if @staff.save
          format.html{redirect_to staffs_path,success:"عملیات با موفقیت انجام شد"}
          format.js{flash.now[:success]="عملیات با موفقیت انجام شد"}
        else
          format.html{redirect_to staffs_path,warning:"متاسفانه عملیات با شکست مواجه شده است"}
          format.js{flash.now[:warning]="متاسفانه عملیات با شکست مواجه شده است"}
        end
      end
  end

  def edit
    if params[:id].present?
      @staff=Staff.find(params[:id])
    end
  end

  def update
    if params[:id].present?
      @staff=Staff.find(params[:id])
      respond_to do |format|
        if @staff.update_attributes(staff_params)
          format.html{redirect_to staffs_path,success:"ویرایش با موفقیت انجام شد"}
          format.js{flash.now[:success]="ویرایش با موفقیت انجام شد"}
        else
          format.html{redirect_to staffs_path,warning:"متاسفانه عملیات ویرایش با موفقیت انجام نشد ، لطفاً با راهبر تماس گیرید"}
          format.js{flash.now[:danger]="متاسفانه عملیات ویرایش با موفقیت انجام نشد ، لطفاً با راهبر تماس گیرید"}
        end
      end
    end
  end

  def destroy
    if params[:id].present?
      @staff=Staff.find(params[:id])
      respond_to do |format|
        if @staff.destroy
          format.html{redirect_to staffs_path,success:"حذف با موفقیت انجام شد"}
          format.js{flash[:success]="حذف با موفقیت انجام شد"}
        else
          format.html{redirect_to staffs_path,warning:"متاسفانه عملیات حذف با موفقیت انجام نشد"}
          format.js{flash[:warning]="متاسفانه عملیات حذف با موفقیت انجام نشد"}
        end
      end
    end
  end
  private
  def staff_params
    params.require(:staff).permit(:f_name,:l_name,:place_id,:username,:password)
  end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_for @staff,remote:true ,html:{"data-toggle":"validator",role:"form"} do |item| %>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title" style="font-family: web_Yekan">

          </h4>
        </div>
        <div class="modal-body">
          <section>
            <div class="form-group form-inline">
              <%= item.text_field :f_name,placeholder:"نام",class:"form-control","data-error":"لطفاً فیلد نام را پر نمایید",required:true  %>
              <div class="help-block with-errors" style="display:inline"><span style="color:#F52559">*</span> اجباری</div>
            </div>
            <div class="form-group form-inline">
              <%= item.text_field :l_name,placeholder:"نام خانوادگی",class:"form-control","data-error":"لطفاً نام خانوادگی را پر نمایید",required:true %>
              <div class="help-block with-errors" style="display:inline"><span style="color:#F52559">*</span> اجباری</div>
            </div>
            <div class="form-group form-inline">
              <%= item.label :place_id,"سمت : " %>
              <%= item.collection_select :place_id,Place.all,:id,:name,{},class:"form-control" %>
            </div>
            <div class="form-group form-inline">
              <%= item.text_field :username,placeholder:"نام کاربری (Username)",class:"form-control","data-error":"لطفاً نام کاربری را پر نمایید",required:true  %>
              <div class="help-block with-errors" style="display:inline">
                <span style="color:#F52559">*<span style="color:#717171">اجباری</span></span>
                <div>نام کاربری باید بین 5 تا 25 کارکتر باشد</div>
              </div>
            </div>
            <div class="form-group form-inline">
              <%= item.password_field :password,placeholder:"رمز عبور (password)",class:"form-control","data-error":"رمز عبور باید حداقل 6 کارکتر باشد",max:25,min:5,required:true  %>
              <div class="help-block with-errors" >
                <span style="color:#F52559">*<span style="color:#717171">اجباری</span></span>
                <div>رمز عبور باید حداقل 6 کارکتر باشد</div>
              </div>
            </div>
          </section>
        </div>
        <div class="modal-footer">
          <%= submit_tag "ثبت",class:"btn  pull-right" %>
          <button type="button" class="btn btn-default" data-dismiss="modal">بستن</button>
        </div>
      </div>
    </div>
<%end%>

app/views/staffs/_staff.html.erb
<tr class="staff_<%= staff.id %>">
  <td class="f_name"><%= staff.f_name %></td>
  <td class="l_name"><%= staff.l_name %></td>
  <td class="place_name"><%= staff.place.name%></td>
  <td class="username"><%= staff.username %></td>
  <td><%= time_ago_in_words(staff.last_login_date, include_seconds: true) if nil? %></td>
  <td>
    <%= link_to  edit_staff_path(staff),class:"btn btn-warning btn-sm",remote:true do %>
        <span class="fa fa-pencil-square-o" style="font-size: 18px"></span>
    <%end%>
    <%= link_to  staff,method: :delete,data:{confirm:"مطمئن هستید که میخواهید پاک کنید ؟"},class:"btn btn-danger btn-sm",remote:true  do %>
        <span class="fa fa-times" style="font-size: 18px"></span>
    <%end%>
  </td>
</tr>

app/views/staffs/create.js.erb
$("#StaffForm").modal("hide");

$("#StaffForm #staff_f_name").val('');
$("#StaffForm #staff_l_name").val('');
$("#StaffForm #staff_username").val('');
$("#StaffForm #staff_password").val('');

$("#alert_respond").text('').fadeOut(300).fadeIn(100);
$("#alert_respond").prepend("<%= j render partial: "layouts/flash_message" %>");

$(".box-body tbody").prepend("<%= j render partial: "staffs/staff",locals: {staff:@staff} %>");
$(".box-body tbody .staff_<%= @staff.id %>").hide.fadeIn(800);



app/views/staffs/destroy.js.erb
$(".box-body tbody .staff_<%= @staff.id %>").fadeOut(300,function () {
  $(this).remove();
  $("#alert_respond").text('').fadeOut(300).fadeIn(100);
  $("#alert_respond").prepend("<%= j render partial: "layouts/flash_message" %>");
});

app/views/staffs/edit.js.erb
if ($("#StaffForm form").length==0 ) {
  $("#StaffForm").addClass("staff_form_edit");
  $("#StaffForm").prepend("<%= j render partial: "staffs/form" %>");
  $("#StaffForm .modal-title").prepend("<span class='fa fa-users'> </span>",
      "<span id='title' style='color: #ffa049;padding-right: 3px'>ویرایش <span style='#33333'>کارمند جدید</span></span>");
  $("#StaffForm .modal-footer input[type=submit]").val("ویرایش").addClass("btn-warning");
  $("#StaffForm form #staff_password").removeAttr("required");
  $("#StaffForm form #staff_password").removeAttr("data-error");
  $("#StaffForm form #staff_password").removeAttr("max");
  $("#StaffForm form #staff_password").removeAttr("min");
  $("#StaffForm").modal("show");
}
else if (!$("#StaffForm form").hasClass("staff_form_edit"))
{
  $("#StaffForm form").remove();
  $("#StaffForm").addClass("staff_form_edit");
  $("#StaffForm").prepend("<%= j render partial: "staffs/form" %>");
  $("#StaffForm .modal-title").prepend("<span class='fa fa-users'> </span>",
      "<span id='title' style='color: #ffa049;padding-right: 3px'>ویرایش <span style='#33333'>کارمند جدید</span></span>");
  $("#StaffForm .modal-footer input[type=submit]").val("ویرایش").addClass("btn-warning");
  $("#StaffForm form #staff_password").removeAttr("required");
  $("#StaffForm form #staff_password").removeAttr("data-error");
  $("#StaffForm form #staff_password").removeAttr("max");
  $("#StaffForm form #staff_password").removeAttr("min");

  $("#StaffForm form .help-block:last").remove();
  $("#StaffForm").modal("show");
}
else if($("#StaffForm form").hasClass("staff_form_edit"))
  $("#StaffForm").modal("show");

app/views/staffs/index.html.erb
<% title 'مدیریت کارمندان' %>
<% javascript "admin/datatables/jquery.dataTables.min" %>
<% javascript "admin/datatables/dataTables.bootstrap.min" %>
<% javascript "validator/validator.min" %>
<% stylesheet "admin/datatables/dataTables.bootstrap.min" %>
<% script "$(document).ready(function(){$('#staff').DataTable({'language':lng_persian});});$('#StaffForm').validator();" %>


<section class="content">
  <section style="margin-bottom:4px">
  <%= link_to  new_staff_path,class:"btn btn-primary",remote:true do %>
     <span class="fa fa-user-plus" style="font-size: 20px"></span>
  <%end%>
    <%= link_to  sessions_path,class:"btn btn-primary" do %>
        <span class="fa fa-chevron-left" style="font-size: 20px"></span>
    <%end%>
  </section>
<div class="box box-warning">
  <div class="box-header with-border">
    <h3 class="box-title" style="font-family: web_Yekan">
      مشخصات کارمندان</h3>
    <div class="box-tools pull-right">
      <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
    </div>
  </div>
  <div class="box-body" style="display: block;">
    <div id="alert_respond"></div>
    <table id="staff" class="table table-striped table-bordered" border="1">
      <thead>
      <tr>
        <th>نام</th>
        <th>نام خانوادگی</th>
        <th>سمت</th>
        <th>نام کاربری</th>
        <th>آخرین تاریخ ورود</th>
        <th>عملیات</th>
      </tr>
      </thead>
      <tbody>
      <% @staffs.each do |staff| %>
        <%  unless staff.place==nil %>
        <%= render partial: "staffs/staff",locals:{staff:staff} %>
        <%end%>
      <%end%>
      </tbody>
    </table>
  </div>
</div>
</section>

<div id="StaffForm" class="modal fade" role="dialog">
<!-- render by js -->
</div>

app/views/staffs/new.js.erb

if ($("#StaffForm form").length==0 ) {
  $("#StaffForm").addClass("staff_form_new");
  $("#StaffForm").prepend("<%= j render partial: "staffs/form" %>");
  $("#StaffForm .modal-title").prepend("<span class='fa fa-users'> </span>",
      "<span id='title' style='color: #00a65a;padding-right: 3px'>ایجاد <span>کارمند جدید</span></span>");
  $("#StaffForm .modal-footer input[type=submit]").val("ایجاد").addClass("btn-success");
  $("#StaffForm").modal("show");
}
else if (!$("#StaffForm form").hasClass("staff_form_new"))
{
  $("#StaffForm form").remove();
  $("#StaffForm").addClass("staff_form_new");
  $("#StaffForm").prepend("<%= j render partial: "staffs/form" %>");
  $("#StaffForm .modal-title").prepend("<span class='fa fa-users'> </span>",
      "<span id='title' style='color: #00a65a;padding-right: 3px'>ایجاد <span>کارمند جدید</span></span>");
  $("#StaffForm .modal-footer input[type=submit]").val("ایجاد").addClass("btn-success");
  $("#StaffForm").modal("show");
}
else if ($("#StaffForm form").hasClass("staff_form_new"))
  $("#StaffForm").modal("show");

app/views/staffs/update.js.erb
$("#StaffForm").modal("hide");
$(".staff_<%= @staff.id %> ").fadeOut(600);
$(".staff_<%= @staff.id %> ").fadeIn(500);
$(".staff_<%= @staff.id %> .f_name").text("<%= @staff.f_name %>");
$(".staff_<%= @staff.id %> .l_name").text("<%= @staff.l_name %>");
$(".staff_<%= @staff.id %> .place_name").text("<%= @staff.place.name %>");
$(".staff_<%= @staff.id %> .username").text("<%= @staff.username %>");
$("#alert_respond").text('').fadeOut(300).fadeIn(100);
$("#alert_respond").prepend("<%= j render partial: "layouts/flash_message" %>");