config/routes.rb
Rails.application.routes.draw do


  root 'sessions#new'
  get  'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :staffs
  resources :places
  resources :features do
    resources :needs
  end
  resources :students
  resources :requests do
    collection do
      get :prints
      get :batch_print
      post :batch
      delete :delete_batch
    end
  end
  resources :sessions
  resources :forms
  resources :request_students
  resources :messages
  resources :import_students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/need.rb
class Need < ApplicationRecord
  has_many :features
  has_many :requests,through: :result_students
  has_many :result_students
  VALID_FARSI_REGEX = /\A[اآبپتثئجچحخدذرزژسشصضطظعغفقکگلمنوهیءأؤّ\s]+\z/
  validates :name, presence: {message: "نام نمی تواند خالی باشد."},
                   length: {within: 2..45, too_long: "نام می تواند حداکثر 45 نویسه باشد.", too_short: "نام باید حداقل 2 نویسه باشد." },
                   format: {with: VALID_FARSI_REGEX, message: "نام باید فارسی باشد."}
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  before_action :staff_logged_in
  layout "staff/admin"
  def index
    if params[:feature_id].present?
      @needs=Feature.find(params[:feature_id]).needs if present?
      @feature=Feature.find(params[:feature_id])
    end

  end

  def new
      if params[:feature_id].present?
        @feature=Feature.find(params[:feature_id])
        @need=Need.new
        @requirement_types=requirement_types
        respond_to do |format|
          format.html
          format.js
        end
      end
  end

  def create
    if params[:feature_id].present?
      @need=Need.new(need_params)
      respond_to do |format|
        if @need.save
          format.html{redirect_to feature_needs_path(params[:feature_id]),success: "عملیات با موفقیت انجام شد"}
          format.js{flash.now[:success]="عملیات با موفقیت انجام شد"}
        else
          format.html{redirect_to feature_needs_path(params[:feature_id]),danger: "متاسفانه عملیات با موفقیت انجام نشد"}
          format.js{flash.now[:danger]="متاسفانه عملیات با موفقیت انجام نشد"}
        end
      end
    end
  end

  def edit
    if params[:feature_id].present?
      @feature=Feature.find(params[:feature_id])
      @need=Need.find(params[:id])
      @requirement_types=requirement_types
    end
  end

  def update
    if params[:feature_id].present?
      @need=Need.find(params[:id])
      respond_to do |format|
        if @need.update_attributes(need_params)
            format.html{redirect_to feature_needs_path(params[:feature_id]),success:"عملیات با موفقیت انجام شد"}
            format.js{flash.now[:success]="عملیات با موفقیت انجام شد"}
        else
          format.html{redirect_to feature_needs_path(params[:feature_id]),danger:"متاسفانه عملیات با موفقیت انجام نشد"}
          format.js{flash.now[:danger]="متاسفانه عملیات با موفقیت انجام نشد"}
        end
      end
    end
  end

  def destroy
    if params[:id].present?
      @need=Need.find(params[:id])
      respond_to do |format|
        if @need.destroy
          format.html{redirect_to feature_needs_path(params[:feature_id]),success:"عملیات با موفقیت انجام شد"}
          format.js{flash.now[:success]="عملیات با موفقیت انجام شد"}
        else
          format.html{redirect_to feature_needs_path(params[:feature_id]),danger:"متاسفانه عملیات با موفقیت انجام نشد"}
          format.js{flash.now[:danger]="متاسفانه عملیات با موفقیت انجام نشد"}
        end
      end
    end
  end
  private
  def need_params
    params.require(:need).permit(:name,:feature_id,:input_type)
  end

end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/views/needs/_form.html.erb
<%= form_for [@feature,@need],remote:true  do |item|   %>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title" style="font-family: web_Yekan"> </h4>
        </div>
        <div class="modal-body">
          <section>
            <div class="form-group form-inline">
              <%= item.hidden_field :feature_id,value:@feature.id %>
              <%= item.label :name,"نام :" %>
              <%= item.text_field :name,placeholder:"نام",class:"form-control","data-error":"لطفاً فیلد نام را پر نمایید",required:true  %>
              <div class="help-block with-errors" style="display:inline"><span style="color:#F52559">*</span> اجباری</div>
            </div>

            <div class="form-group form-inline">
              <%= item.label :input_type,"نوع فیلد :" %>
              <%= item.select :input_type,requirement_types.collect { |key,value| [value,key] },include_blank:true,class:"form-control","data-error":"لطفاً نوع فیلد را انتخاب نمایید",required:true  %>
              <div class="help-block with-errors" style="display:inline"><span style="color:#F52559">*</span> اجباری</div>
            </div>
          </section>
        </div>
        <div class="modal-footer">
          <%= submit_tag "ثبت",class:"btn pull-right" %>
          <button type="button" class="btn btn-default" data-dismiss="modal">بستن</button>
        </div>
      </div>
    </div>
<%end%>

app/views/needs/_need.html.erb
<tr class="need_<%= need.id %>">
  <td class="name"><%= need.name %></td>
  <td class="type"><%= requirement_types[need.input_type] %></td>
  <td>
    <%= link_to  edit_feature_need_path(feature,need.id),class:"btn btn-warning btn-sm",remote:true do %>
        <span class="fa fa-pencil-square-o" style="font-size: 18px"></span>
    <%end%>
    <%= link_to  feature_need_path(feature,need.id),method: :delete,data:{confirm:"مطمئن هستید که میخواهید پاک کنید ؟"},class:"btn btn-danger btn-sm",remote:true  do %>
        <span class="fa fa-times" style="font-size: 18px"></span>
    <%end%>
  </td>
</tr>

app/views/needs/create.js.erb
$("#NeedForm").modal("hide");
$("#NeedForm form #name").val('');
$("#alert_respond").text('').fadeOut(300).fadeIn(100);
$("#alert_respond").prepend("<%= j render partial: "layouts/flash_message" %>");

$("tbody").prepend("<%= j render partial: "needs/need",locals: {need:@need,feature:params[:feature_id]} %>");
$("tbody .need_<%= @need.id %>").hide.fadeIn(800);

app/views/needs/destroy.js.erb
$("tbody .need_<%= @need.id %>").fadeOut(300,function () {
  $(this).remove();
  $("#alert_respond").text('').fadeOut(300).fadeIn(100);
  $("#alert_respond").prepend("<%= j render partial: "layouts/flash_message" %>");

});

app/views/needs/edit.js.erb
if ($("#NeedForm form").hasClass("new_need")) {$("#NeedForm form").remove()}
else if ($("#NeedForm form").hasClass("edit_need")) {
  $("#NeedForm form").remove();
  $("#NeedForm").prepend("<%= j render partial: "needs/form" %>");
  $("#NeedForm .modal-title").prepend("<span class='fa fa-edit" + "'> </span>",
      "<span id='title' style='color: #ffbc00;padding-right: 3px'>ویرایش <span>پیش نیاز </span></span>");
  $("#NeedForm .modal-footer input[type=submit]").val("ویرایش").addClass("btn-warning");
  $("#NeedForm").modal("show");
}
else {
  $("#NeedForm").prepend("<%= j render partial: "needs/form" %>");
  $("#NeedForm .modal-title").prepend("<span class='fa fa-edit" + "'> </span>",
      "<span id='title' style='color: #ffbc00;padding-right: 3px'>ویرایش <span>پیش نیاز </span></span>");
  $("#NeedForm .modal-footer input[type=submit]").val("ویرایش").addClass("btn-warning");
  $("#NeedForm").modal("show");
}

app/views/needs/index.html.erb
<%= title "نیاز های ماژول" %>
<section class="content">
  <section style="margin-bottom:4px">
    <%= link_to  new_feature_need_path,class:"btn btn-primary",remote:true do %>
        <span class="fa fa-plus" style="font-size: 20px"></span>
    <%end%>
    <%= link_to  features_path,class:"btn btn-primary" do %>
        <span class="fa fa-chevron-left" style="font-size: 20px"></span>
    <%end%>
  </section>

  <div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title">پیش نیاز های <span style="color: #0d6aad"><%= Feature.find(params[:feature_id]).name if present? %></span></h3>
      <div class="box-tools pull-right">
        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>
      <div class="box-body" style="display: block;">
        <div id="alert_respond"></div>
        <table class="table table-responsivee">
          <thead>
          <tr>
            <th>نام</th>
            <th>نوع</th>
            <th>عملیات</th>
          </tr>
          </thead>
          <tbody>
          <% @needs.each do |need| %>
            <%= render partial: "needs/need",locals: {need:need,feature:params[:feature_id]} %>
          <%end%>

          </tbody>
        </table>
      </div>
    </div>
  </section>
<div id="NeedForm" class="modal fade" role="dialog"></div>

app/views/needs/new.js.erb
if ($("#NeedForm form").hasClass("edit_need")) {$("#NeedForm form").remove()}
else if ($("#NeedForm form").hasClass("new_need")) { $("#NeedForm").modal("show");}
else
{
  $("#NeedForm").prepend("<%= j render partial: "needs/form"%>");
  $("#NeedForm .modal-title").prepend("<span class='fa fa-plus-circle"+ "'> </span>",
      "<span id='title' style='color: #00a65a;padding-right: 3px'>ایجاد <span>پیش نیاز ماژول</span></span>");
  $("#NeedForm .modal-footer input[type=submit]").val("ایجاد").addClass("btn-success");
  $("#NeedForm form").addClass("new_need");
  $("#NeedForm").modal("show");
}

app/views/needs/update.js.erb
$("#NeedForm").modal("hide");
$(".need_<%= @need.id %>").fadeOut(600);
$(".need_<%= @need.id %>").fadeIn(500);
$(".need_<%= @need.id %> .name").text("<%= @need.name %>");
$(".need_<%= @need.id %> .type").text("<%=requirement_types.key(@need.input_type)  %>");
$("#alert_respond").text('').fadeOut(300).fadeIn(100);
$("#alert_respond").prepend("<%= j render partial: "layouts/flash_message" %>");