config/routes.rb
Rails.application.routes.draw do


  root 'sessions#new'
  get  'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :staffs
  resources :places
  resources :features do
    resources :needs
  end
  resources :students
  resources :requests do
    collection do
      get :prints
      get :batch_print
      post :batch
      delete :delete_batch
    end
  end
  resources :sessions
  resources :forms
  resources :request_students
  resources :messages
  resources :import_students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  has_one :refer
  belongs_to :feature
  belongs_to :student
  has_many :needs,through: :result_students
  has_many :result_students
  scope :active_place_related ,lambda { |place| where(module_pointer:place,status:1) } # module_pointer points to requests 'stage' which is related to different Places
  scope :requests_student,lambda{|student| where(student_id:student).order(updated_at: :desc)}
  scope :find_by_array,lambda{|array| find(array)}
  scope :request_print,lambda{|place| where(status: 2,module_pointer:place)}
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  include BatchRequestHelper
  before_action :staff_logged_in ,except: :create
  before_action :student_logged_in ,only: :create
  layout "staff/admin"

  def index
# clear_batch
    place=current_user.place_id if present?
    @requests=Request.active_place_related(place)
    @batch=get_batch

  end
  
  def show
     @request=Request.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end
  def new
  # @request=Request.new(request_params)
  end

  def create
    student=current_user
    access=Request.where('created_at >= ?',1.week.ago).where(student_id:current_user.id).count
      if access > 5 #limit count for request students
    feature=Feature.find(params[:feature_id])
    first_confirm=get_module_routes(feature.id).first # get first value in module routes helper-]
    status=1


        if !feature.nil?
          valid=false
          feature.needs.map do |need|

            if !params[:"form_#{need.id}"].present? && need.input_type==3 || params[:"form_#{need.id}"].present? && need.input_type!=3
                # validation for dynamic result student
                # requirement_types => 1: number , 2: character , 3: check box (true ot false)
              unless params[:"form_#{need.id}"].present?
                params[:"form_#{need.id}"]=false
              end

                  case need.input_type
                    when requirement_types.key("عدد")
                      params[:"form_#{need.id}"].match(/\A[+-]?\d+?(\.\d+)?\Z/)!=nil ? valid=true : valid=false
                    when requirement_types.key("کارکتر")
                      params[:"form_#{need.id}"].match(/\A[اآبپتثئجچحخدذرزژسشصضطظعغفقکگلمنوهیءأؤّ\s]+\z/)!=nil ? valid=true : valid=false
                    when requirement_types.key("گزینه")
                      params[:"form_#{need.id}"]==true || params[:"form_#{need.id}"]==false ? valid=true : valid=false
                  end

                   # if it was valid go for save data
                if valid==true
                  Request.transaction do
                      if request=Request.create(student_id:student.id,feature_id:feature.id,status:status,module_pointer: first_confirm)
                        respond_to do |format|
                          if ResultStudent.create(request_id:request.id,need_id:need.id,value:params[:"form_#{need.id}"])
                              format.js{flash.now[:success]="درخواست شما با موفقیت فرستاده شد"}
                          else
                            format.js{flash.now[:warning]="متاسفان درخواست شما فرستاده نشد"}
                              raise ActiveRecord::Rollback
                          end
                                                 
                        end
                      end
                  end
                else
                  # when not valid
                  respond_to do |format|
                    format.js{flash.now[:danger]=" اشتباه می باشد لطفاً مقادیر را صحیح وارد کنید #{feature.name} مقادیری پر شده برای درخواست "}
                  end
                end
            else
                  # when not correct params for field needs of feature
              respond_to do |format|
                format.js{flash.now[:warning]="لطفاً نیازمندی های درخواست مورد نظرتان را به دقت وارد نمایید"}
              end
              break # break in loop needs of feature
            end


          end
        else
           # if not fimd feature in params[:featue_id]
          respond_to do |format|
            format.js{flash.now[:warning]="لطفاً نیازمندی های درخواست مورد نظرتان را به دقت وارد نمایید"}
          end
        end
      else 
        respond_to do |format|
          format.js{flash.now[:danger]="محدوده ارسال درخواست توسط شما زیاد بوده است , لطفاً در هفته های آتی درخواست خود را ارسال کنید"}
        end
      end
  end


  def edit
  end

  def update

    
    # unless user_type==Staff && req.module_pointer == @current_user.place_id && req.status ==  1  #if you aren't staff user OR insufficient place OR request's status isnt 'in progress'
    #    redirect_to request.referer || requests_path,danger: "شما اجازه تغییر این درخواست را ندارید."
    #   return
    # end
    req = Request.find(params[:id]) unless params[:id].to_i==-1 # return request if params[:id] != -1
    case params[:type]
      when "Confirm"
        unless params[:id]=='-1'     #note param[:id] != -1 => Confirm for one requests ( staffs != staff.last)
          mod = get_module_routes(req.feature_id)
          if mod.size > mod.index(req.module_pointer)+1
            # confrim request and next staff
            Request.transaction do
              req.module_pointer = mod[mod.index(req.module_pointer)+1] #Approve
              req.save
              respond_to do |format|
                @refer=Refer.create(staff_id: current_user.id, request_id: req.id) #Logging #TODO add message_id
                if @refer
                  format.js{flash.now[:success]="عملیات با موفقیت انجام شد"}
                else
                  format.js{flash.now[:danger]="متاسفانه عملیات با موفقیت انجام نشد"}
                end
              end
            end
          else
            #confirm request and create refer (ready for print request)
            Request.transaction do
              req.status = 2 #Certificate
              req.save
              respond_to do |format|
                @refer=Refer.create(staff_id:current_user.id, request_id: req.id)#TODO add message_id
                if @refer
                  format.js{flash.now[:success]="عملیات با موفقیت انجام شد"}
                else
                  format.js{flash.now[:danger]="متاسفانه عملیات با موفقیت انجام نشد"}
                end
              end
            end
          end
          
        else  #note param[:id] : -1=> Confirm for all requests

          get_requests_batch.each do |rq|
            mod = get_module_routes(rq.feature_id)
            if mod.size > mod.index(rq.module_pointer)+1
              Request.transaction do
                rq.module_pointer = mod[mod.index(rq.module_pointer)+1] #Approve
                rq.save
                
                respond_to do |format|
                  if Refer.create(staff_id: current_user.id, request_id: rq.id) #Logging #TODO add message_id
                    format.js{flash.now[:success]="عملیات با موفقیت انجام شد"}
                    @status_respond=true
                    @batch=get_batch

                  else
                    format.js{flash.now[:danger]="متاسفانه عملیات با موفقیت انجام نشد"}
                  end
                end
              end
            else
              Request.transaction do
                rq.status = 2 #Certificate
                rq.save
               
                respond_to do |format|
                  if Refer.create(staff_id:current_user.id, request_id: rq.id)#TODO add message_id
                    format.js{flash.now[:success]="عملیات با موفقیت انجام شد"}
                    @status_respond=true
                    @batch=get_batch
                   
                  else
                    format.js{flash.now[:danger]="متاسفانه عملیات با موفقیت انجام نشد"}
                  end
                end
              end
            end
          end
           # clear_batch #note clear all element in batch list
        end
        
    when "Reject"
      Request.transaction do
        req.status = 3 #Rejected
        req.save
        @refer=Refer.create(staff_id: current_user.id, request_id: req.id,message_id:params[:message])
        respond_to do |format|
       if @refer
         format.js{flash.now[:success]="درخواست انتخابی شما با موفقیت رد شد"}
         else 
         format.js{flash.now[:danger]="درخواست انتخابی شما با موفقیت رد شد"}
         end

        end
      end

    end
    @batch=get_batch

  end

  def destroy
  end


  def batch_pdf


    # respond_to do |format|   buggy
    #   format.html
    #   format.pdf do
    #     render :pdf => "invoice"
    #     # render pdf:"asa",template:"forms/index.html.erb", :formats => [:html], :locals => { :forms=>requests }
    #     # render pdf: "file_name"   # Excluding ".pdf" extension.
    #   end
    # end

  end

  def batch_print
    
  render "forms/index",layout: "form/index",locals: {forms:get_requests_batch}

  end

  def batch # create request to batch
    if params[:id].present?
      respond_to do |format|
          unless has_batch?(params[:id])
             add_batch(params[:id])
             @batch=get_batch
             format.js{flash.now[:success]="درخواست با موفقیت در لیست چاپی قرار گرفت"}
          else
            @batch=get_batch
            format.js{flash.now[:warning]="این درخواست قبلاً در لیست  قرار داده شده"}
          end
        end
    end
  end

  def delete_batch
    clear_batch # clear session batch print
      respond_to do |format|
        format.js{flash.now[:success]="لیست چاپی با موفقیت پاک شد"}
      end
  end

  def prints
    @requests=Request.request_print(current_user.place_id)
    @batch=get_batch

    
  end
 
  private
  def request_params
    params.require(:request).permit(:feature_id)
  end
  

  def get_requests_batch # return requests as type active record into batch
    Request.find_by_array(get_batch).to_a
  end




end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_details.html.erb
<div class="col-lg-12 col-md-12">
  <div class="col-lg-5" style="margin-bottom: 5px">
    <span class="glyphicon glyphicon-time"></span>
    <span>زمان ارسال درخواست : </span>
    <span> <%= time_ago_in_words(request.created_at) %> پیش  </span>
  </div>
</div>

<table class="table table-striped table-bordered table-hover table-responsive" style="overflow-x: auto">
    <tr>
      <% request.needs.each do |need| %>
      <th><%= need.name %></th>
    </tr>
    <tr>
      <% request.result_students.each do |result| %>
      <td><%=
        if need.input_type==3
        result.value=='f' ?  "خیر" : "بله"
          else
            result.value
         end
      %></td>
      <%end%>
    </tr>
      <%end%>
</table>

app/views/requests/_request.html.erb
<% feature = get_module_routes(request.feature_id) %>
<tr class="request_<%=request.id %>">
  <td><%= request.student.f_name %></td>
  <td><%= request.student.l_name %></td>
  <td><%= request.student.student_code %></td>
  <td><%= field_of_study[request.student.field][:major] %></td>
  <td><%= link_to "جزئییات",request_path(request.id),remote:true,class:"btn btn-xs btn-warning"%></td>
  <td><%= request.feature.name %></td>
  <td>
    <%#= link_to request_path(id: request.id, type: "Certficate"), method: :put ,class:"btn btn-success" do %>
    <%# if feature.last == request.module_pointer  %>

        <!-- link for create request to batch --> 
        <%= link_to request_path(id:request.id,type:"Confirm"),method: :put,remote:true,class:"btn btn-sm btn-success print","data-loading-text":"<i class='fa fa-circle-o-notch fa-spin'></i> در حال پردازش" do %>
            <i class="fa fa-print"></i>
            <span>تایید</span>
        <%end%>

      <%#= link_to request_path(id: request.id, type: "Confirm"),remote:true, method: :put, class:"btn btn-sm btn-info" do %>
          <!--<i class="fa fa-check-square-o"></i>-->
          <!--<span>تایید</span>-->
      <%#end%>  
        <!--<%#= link_to batch_requests_path(id: request.id),remote:true, method: :post, class:"btn btn-sm btn-info" do %>-->
          <!--<i class="fa fa-check-square-o"></i>-->
          <!--<span>تایید</span>-->
      <!--<%#end%>-->
        

    
    <%= link_to messages_path(request_id:request.id),data: {confirm:"آیا مطمئن هستید که میخواهید این درخواست را لغو کنید ؟"},remote:true,class:"btn btn-sm btn-danger" do   %>
        <i class="fa fa-times"></i>
        <span>رد کردن</span>
    <%end%>
  </td>
</tr>

app/views/requests/_request_prints.html.erb
<% feature = get_module_routes(request.feature_id) %>
<tr class="request_<%=request.id %>">
  <td><%= request.student.f_name %></td>
  <td><%= request.student.l_name %></td>
  <td><%= request.student.student_code %></td>
  <td><%= field_of_study[request.student.field][:major] %></td>
  <td><%= link_to "جزئییات",request_path(request.id),remote:true,class:"btn btn-xs btn-warning"%></td>
  <td><%= request.feature.name %></td>
  <td>
    <% if feature.last == request.module_pointer  %>
        <!-- link for create request to batch -->
        <%= link_to batch_requests_path(id:request.id),method: :post,remote:true,class:"btn btn-sm btn-success print","data-loading-text":"<i class='fa fa-circle-o-notch fa-spin'></i> در حال پردازش" do %>
            <i class="fa fa-print"></i>
            <span>صدور</span>
        <%end%>
    <% end %>
  </td>
</tr>

app/views/requests/batch.js.erb
$("#alert_respond").html("<%= j render partial: "layouts/flash_message" %>");
$("#count_batch").text(parseInt(<%=@batch.count %>));
$("#count_batch").fadeOut(100).fadeIn(1000);

app/views/requests/create.js.erb
len=$("form").length;
for (var i=0;i<len;i++) { $("form")[i].reset()} // clear all data in the form 
swal("init");

<% if flash.now[:warning].present? %>
swal({
    title:"! هشدار",
    text:"<%=flash.now[:warning] %>",
    type:"warning",
    confirmButtonText:"باشه چشم"});
<% elsif flash.now[:success].present? %>
swal({
    title:"انجام شد",
    text:"<%=flash.now[:success] %>",
    type:"success",
    confirmButtonText:"ممنون"});

<% elsif flash.now[:danger].present? %>
swal({
    title:" ! خطا ",
    text:"<%=flash.now[:danger] %>",
    type:"danger",
    confirmButtonText:"باشه چشم"});
<%end%>

app/views/requests/delete_batch.js.erb
$("#alert_respond").text('');
$("#count_batch").hide(100).fadeIn(800).text('0');
var el='<div class="alert alert-success alert-dismissable fade in"><p><%=flash[:success] %></p></div>';
$("#alert_respond").append(el);

app/views/requests/destroy.html.erb
<h1>Requests#destroy</h1>
<p>Find me in app/views/requests/destroy.html.erb</p>

app/views/requests/edit.html.erb
<h1>Requests#edit</h1>
<p>Find me in app/views/requests/edit.html.erb</p>

app/views/requests/index.html.erb
<% title 'درخواست ها' %>
<% javascript "admin/datatables/jquery.dataTables.min" %>
<% javascript "admin/datatables/dataTables.bootstrap.min" %>
<% javascript "validator/validator.min" %>
<% javascript "requests" %>
<% stylesheet "admin/datatables/dataTables.bootstrap.min" %>
<% stylesheet "requests" %>
<% stylesheet "messages" %>
<% script "$(document).ready(function(){$('#requests').DataTable({'language':lng_persian});})"%>
<section class="content">
  <section style="margin-bottom:4px">

    <%= link_to  sessions_path,class:"btn btn-primary" do %>
        <span class="fa fa-chevron-left" style="font-size: 20px"></span>
    <%end%>

  </section>
  <div class="box box-info">
    <div class="box-header with-border">
      <h3 class="box-title" style="font-family: web_Yekan">درخواست دانشجو ها</h3>
      <div class="box-tools pull-right">
        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>

    <div class="box-body" style="overflow-x: auto">
      <div id="alert_respond"></div>

      <table id="requests" class="table table-striped table-bordered table-responsive table-hover" border="1">
        <thead>
        <tr>
          <th>نام</th>
          <th>نام خانوادگی</th>
          <th>کد دانشجویی</th>
          <th>رشته</th>
          <th>جزئییات</th>
          <th>نوع درخواست</th> <!-- madule -->
          <th>عملیات</th>
        </tr>
        </thead>
        <tbody class="table-responsive">
        <% @requests.each do |request| %>
            <%= render partial: "requests/request",locals:{request:request} %>
        <%end%>
        </tbody>
      </table>
    </div>
  </div>
</section>

<div id="DetailsRequest" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header" style="background-color: #00C0EF">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" style="color: #ffffff;font-family: web_Yekan"> student name </h4>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-right" data-dismiss="modal">بستن</button>
      </div>
    </div>

  </div>
</div>



<div id="DeleteRequest" class="modal fade" role="dialog">
  
</div>

app/views/requests/prints.html.erb
<% title 'درخواست ها' %>
<% javascript "admin/datatables/jquery.dataTables.min" %>
<% javascript "admin/datatables/dataTables.bootstrap.min" %>
<% javascript "validator/validator.min" %>
<% javascript "requests" %>
<% stylesheet "admin/datatables/dataTables.bootstrap.min" %>
<% stylesheet "requests" %>
<% stylesheet "messages" %>
<% script "$(document).ready(function(){$('#requests').DataTable({'language':lng_persian});})"%>
<section class="content">
  <section style="margin-bottom:4px">

    <%= link_to  sessions_path,class:"btn btn-primary" do %>
        <span class="fa fa-chevron-left" style="font-size: 20px"></span>
    <%end%>

  </section>
  <div class="box box-info">
    <div class="box-header with-border">
      <h3 class="box-title">درخواست دانشجو ها</h3>
      <div class="box-tools pull-right">
        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>

    <div class="box-body" style="overflow-x: auto">
      <div id="alert_respond"></div>
      <section>
        <div class="col-lg-12">
          <div class="bacth_print col-lg-4" style="">
            <i class="glyphicon glyphicon-print"></i>
            <span>لیست درخواست ها آماده برای صدور <strong> : </strong></span>
            <span id="count_batch"> <%=@batch.count%> </span>
            <% if get_module_routes.map{ |s,key| key.last==current_user.place_id}.first  %>
                <a class="btn btn-primary pull-left" href="<%= batch_print_requests_path %>" target="_blank" title="چاپ لیست"><i class="fa fa-print" ></i></a>
            <% end %>
            <%= link_to delete_batch_requests_path,remote:true,method: :delete,class:"btn btn-danger pull-left",title:"پاک کردن تمامی درخواست ها از لیست چاپ" do%>
                <i class="fa fa-trash-o"></i>
            <%end%>

          </div>

        </div>
      </section>

      <table id="requests" class="table table-striped table-bordered table-responsive table-hover" border="1">
        <thead>
        <tr>
          <th>نام</th>
          <th>نام خانوادگی</th>
          <th>کد دانشجویی</th>
          <th>رشته</th>
          <th>جزئییات</th>
          <th>نوع درخواست</th> <!-- madule -->
          <th>عملیات</th>
        </tr>
        </thead>
        <tbody class="table-responsive">
        <% @requests.each do |request| %>
            <%= render partial: "requests/request_prints",locals:{request:request} %>
        <%end%>
        </tbody>
      </table>
    </div>
  </div>
</section>

<div id="DetailsRequest" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header" style="background-color: #00C0EF">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" style="color: #ffffff;font-family: web_Yekan"> student name </h4>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-right" data-dismiss="modal">بستن</button>
      </div>
    </div>

  </div>
</div>



<div id="DeleteRequest" class="modal fade" role="dialog">

</div>

app/views/requests/show.js.erb
$("#DetailsRequest .modal-body").text('');
$("#DetailsRequest .modal-title").text('');
$("#DetailsRequest").modal("show");
$("#DetailsRequest .modal-title").text( "<%=@request.student.f_name %>  <%=@request.student.l_name %> ");
$("#DetailsRequest .modal-body").prepend("<%= j render partial: "requests/details",locals: {request:@request} %>");

app/views/requests/update.js.erb
$("#DeleteRequest").modal("hide");
$("#alert_respond").html("<%= j render partial: "layouts/flash_message" %>");
<% if @refer.present? %>
  $("#requests .request_<%= @refer.request_id unless @refer.nil? %>").fadeOut(500).hide(1000);
<%end%>
<% if @status_respond==true %>
  <% @batch.each do |id| %>
  $("#requests .request_<%= id %>").fadeOut(500).hide(1000);
  <%end%>
$("#count_batch").text(parseInt($("#count_batch").text())-<%=@batch.size %>);
<% clear_batch %>
<%end%>