config/routes.rb
Rails.application.routes.draw do


  root 'sessions#new'
  get  'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :staffs
  resources :places
  resources :features do
    resources :needs
  end
  resources :students
  resources :requests do
    collection do
      get :prints
      get :batch_print
      post :batch
      delete :delete_batch
    end
  end
  resources :sessions
  resources :forms
  resources :request_students
  resources :messages
  resources :import_students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :staffs
  VALID_FARSI_REGEX = /\A[اآبپتثئجچحخدذرزژسشصضطظعغفقکگلمنوهیءأؤّ\s]+\z/
  validates :name, presence: {message: "نام نمی تواند خالی باشد."},
                   length: {within: 2..45, too_long: "نام می تواند حداکثر 45 نویسه باشد.", too_short: "نام باید حداقل 2 نویسه باشد." },
                   uniqueness: {message: "این نام قبلاً استفاده شده است."},
                   format: {with: VALID_FARSI_REGEX, message: "نام باید فارسی باشد."}

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :staff_logged_in
  layout "staff/admin"
  def index
    @places=Place.all
  end

  def new
    @place=Place.new
  end
  def create
    @place=Place.new(place_params)
      respond_to do |format|
        if @place.valid? && @place.save
         format.html{redirect_to places_path,success:"با موفقیت اضافه شد #{@place.name} سمت "}
         format.js{flash.now[:success]="با موفقیت اضافه شد #{@place.name} سمت "}
        else
          format.html{redirect_to places_path,danger:"عملیات با شکست مواجه شد"}
          format.js{flash.now[:danger]="عملیات با شکست مواجه شد"}
        end
      end
  end
  def edit
    if params[:id].present?
    @place=Place.find(params[:id])
    end
  end
  def update
    respond_to do |format|
      @place=Place.find(params[:id])
        if @place.update_attributes(place_params)
          format.html{redirect_to places_path,success:"عملیات با موفقیت انجام شد"}
          format.js{flash.now[:success]="عملیات با موفقیت انجام شد"}
        else
          format.html{redirect_to places_path,danger:"عملیات با شکست مواجه شد"}
          format.js{flash.now[:danger]="عملیات با شکست مواجه شد"}
        end
      end
  end

  def destroy
    if params[:id].present?
        respond_to do |format|
          @place=Place.find(params[:id])
          if @place.destroy
          format.html{redirect_to places_path,success:"عملیات با موفقیت انجام شد"}
          format.js{flash.now[:success]="عملیات با موفقیت انجام شد"}
          else
          format.html{redirect_to places_path,danger:"عملیات با شکست مواجه شد"}
          format.js{flash.now[:danger]="عملیات با شکست مواجه شد"}
        end
      end
    end
  end
  private
  def place_params
    params.require(:place).permit(:name)
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%=form_for @place,remote:true,html:{"data-toggle":"validator",role:"form"} do |item| %>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title" style="font-family: web_Yekan">
            <!-- added by jquery -->
          </h4>
        </div>
        <div class="modal-body">
          <div class="form-group form-inline">
            <%= item.text_field :name,placeholder:"نام سمت",class:"form-control","data-error":"لطفاً فیلد نام را پر نمایید",required:true  %>
            <div class="help-block with-errors" style="display:inline"><span style="color:#F52559">*</span> اجباری</div>
          </div>
        </div>
        <div class="modal-footer">
          <%= submit_tag "ثبت",class:"btn  pull-right" %>
          <button type="button" class="btn btn-default" data-dismiss="modal">بستن</button>
        </div>
      </div>
    </div>
<%end%>

app/views/places/_place.html.erb
<div class="col-lg-2 inline place_<%=place.id%>">
  <div class="col-lg-12 btn btn-info" style="margin:3px">
    <i class="fa fa-user fa-5x"></i><br/>
    <%= place.name %>
    <div>
      <%= link_to edit_place_path(place),class: "btn btn-warning btn-sm",remote:true do  %>
          <span class="fa fa-pencil-square-o"></span>
      <%end%>
      <%= link_to place,class: "btn btn-danger btn-sm",method: :delete,data:{confirm:"مطمئن هستید که میخواهید پاک کنید ؟"},remote:true  do  %>
          <span class="fa fa-times"></span>
      <%end%>
  </div>
  </div>
</div>

app/views/places/create.js.erb
$("#Placeform").modal('hide');
$(".PlaceName").val('');
$("#alert_respond").text('').fadeOut(300).fadeIn(100);
$("#alert_respond").prepend("<%= j render partial: "layouts/flash_message" %>");
$(".placesbody:last").prepend('<%= j render partial: "place",locals: {place:@place}%>');
$(".place_<%=@place.id %>").hide().fadeIn(1000);

app/views/places/destroy.js.erb
$(".place_<%=@place.id%>").fadeOut(400,function () {
  $(this).remove();
  $("#alert_respond").text('').fadeOut(300).fadeIn(100);
  $("#alert_respond").prepend("<%= j render partial: "layouts/flash_message" %>");
});

app/views/places/edit.js.erb
if ($("#Placeform form").length==0)
{
  $("#Placeform").addClass("Place_form_edit");
  $("#Placeform").prepend("<%= j render partial:"places/form" %>");
  $("#Placeform .modal-title").prepend("<span class='fa fa-users'></span>",
      "<span id='title' style='color: #ffa049;padding-right: 3px'> ویرایش <span style='color: #333333' >سمت جدید</span></span>");
  $("#Placeform .modal-footer input[type=submit]").val("ویرایش").addClass("btn-warning");
  $("#Placeform").modal("show");
}
else if (!$("#Placeform form").hasClass("Place_form_edit"))
{
  $("#Placeform form").remove();
  $("#Placeform").addClass("Place_form_edit");
  $("#Placeform").prepend("<%= j render partial:"places/form" %>");
  $("#Placeform .modal-title").prepend("<span class='fa fa-users'></span>",
      "<span id='title' style='color: #ffa049;padding-right: 3px'>ویرایش <span style='color: #333333'>سمت جدید</span></span>");
  $("#Placeform .modal-footer input[type=submit]").val("ویرایش").addClass("btn-warning");
  $("#Placeform").modal("show");
}
else if ($("#Placeform").hasClass("Place_form_edit"))
  $("#Placeform").modal("show");

app/views/places/index.html.erb
<% title 'مدیریت کارمندان' %>
<% javascript "validator/validator.min" %>
<% script "$('#CreatePlace').validator();$('#EditPlace').validator();" %>
<% form_error(@place) %>


<section class="content">
  <section style="margin-bottom:4px">
    <%= link_to  new_place_path,class:"btn btn-primary",remote:true do %>
        <span class="fa fa-plus" style="font-size: 20px"></span>
    <%end%>
    <%= link_to  sessions_path,class:"btn btn-primary" do %>
        <span class="fa fa-chevron-left" style="font-size: 20px"></span>
    <%end%>
  </section>

  <div class="box box-success">
    <div class="box-header with-border">
      <h3 class="box-title">سمت</h3>
      <div class="box-tools pull-right">
        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
      </div>
    </div>
      <div class="box-body" style="display: block;">
        <div id="alert_respond"></div>
        <div class="col-lg-12 placesbody">
        <% @places.each do |place| %>
        <%= render partial: "place",locals: {place:place} %>
        <%end%>
        </div>
      </div>
    </div>
</section>


<div id="Placeform" class="modal fade" role="dialog">
<!-- render form -->
</div>

app/views/places/new.js.erb
if ($("#Placeform form").length==0 )
{
  $("#Placeform").addClass("Place_form_new");
  $("#Placeform").prepend("<%= j render partial:"places/form" %>");
  $("#Placeform .modal-title").prepend("<span class='fa fa-users'> </span>",
      "<span id='title' style='color: #00a65a;padding-right: 3px'>ایجاد</span>");
  $("#Placeform .modal-footer input[type=submit]").val("ایجاد").addClass("btn-success");
  $("#Placeform").modal("show");
}
else if (!$("#Placeform form").hasClass("Place_form_new"))
{
  $("#Placeform form").remove();
  $("#Placeform").addClass("Place_form_new");
  $("#Placeform").prepend("<%= j render partial:"places/form" %>");
  $("#Placeform .modal-title").prepend("<span class='fa fa-users'> </span>",
      "<span id='title' style='color: #00a65a;padding-right: 3px'>ایجاد</span><span>سمت جدید</span>");
  $("#Placeform .modal-footer input[type=submit]").val("ایجاد").addClass("btn-success");
  $("#Placeform").modal("show");
}
else if ($("#Placeform").hasClass("Place_form_new"))
  $("#Placeform").modal("show");


app/views/places/update.js.erb
$(".place_<%=@place.id %>").fadeOut(500,function(){
  $(this).remove();
  $("#alert_respond").text('').fadeOut(300).fadeIn(100);
  $("#alert_respond").prepend("<%= j render partial: "layouts/flash_message" %>");
  $(".placesbody:last-child").prepend('<%= j render partial: "place",locals: {place:@place}%>');
});
$("#Placeform").modal("hide");